import { TarotCardData } from "../types/tarot";

export const TAROT_CARDS: TarotCardData[] = [
  // Major Arcana (22)
  { id: "major-0", name: "The Fool" },
  { id: "major-1", name: "The Magician" },
  { id: "major-2", name: "The High Priestess" },
  { id: "major-3", name: "The Empress" },
  { id: "major-4", name: "The Emperor" },
  { id: "major-5", name: "The Hierophant" },
  { id: "major-6", name: "The Lovers" },
  { id: "major-7", name: "The Chariot" },
  { id: "major-8", name: "Strength" },
  { id: "major-9", name: "The Hermit" },
  { id: "major-10", name: "Wheel of Fortune" },
  { id: "major-11", name: "Justice" },
  { id: "major-12", name: "The Hanged Man" },
  { id: "major-13", name: "Death" },
  { id: "major-14", name: "Temperance" },
  { id: "major-15", name: "The Devil" },
  { id: "major-16", name: "The Tower" },
  { id: "major-17", name: "The Star" },
  { id: "major-18", name: "The Moon" },
  { id: "major-19", name: "The Sun" },
  { id: "major-20", name: "Judgement" },
  { id: "major-21", name: "The World" },

  // Wands (14)
  { id: "wands-1", name: "Ace of Wands" },
  { id: "wands-2", name: "Two of Wands" },
  { id: "wands-3", name: "Three of Wands" },
  { id: "wands-4", name: "Four of Wands" },
  { id: "wands-5", name: "Five of Wands" },
  { id: "wands-6", name: "Six of Wands" },
  { id: "wands-7", name: "Seven of Wands" },
  { id: "wands-8", name: "Eight of Wands" },
  { id: "wands-9", name: "Nine of Wands" },
  { id: "wands-10", name: "Ten of Wands" },
  { id: "wands-11", name: "Page of Wands" },
  { id: "wands-12", name: "Knight of Wands" },
  { id: "wands-13", name: "Queen of Wands" },
  { id: "wands-14", name: "King of Wands" },

  // Cups (14)
  { id: "cups-1", name: "Ace of Cups" },
  { id: "cups-2", name: "Two of Cups" },
  { id: "cups-3", name: "Three of Cups" },
  { id: "cups-4", name: "Four of Cups" },
  { id: "cups-5", name: "Five of Cups" },
  { id: "cups-6", name: "Six of Cups" },
  { id: "cups-7", name: "Seven of Cups" },
  { id: "cups-8", name: "Eight of Cups" },
  { id: "cups-9", name: "Nine of Cups" },
  { id: "cups-10", name: "Ten of Cups" },
  { id: "cups-11", name: "Page of Cups" },
  { id: "cups-12", name: "Knight of Cups" },
  { id: "cups-13", name: "Queen of Cups" },
  { id: "cups-14", name: "King of Cups" },

  // Swords (14)
  { id: "swords-1", name: "Ace of Swords" },
  { id: "swords-2", name: "Two of Swords" },
  { id: "swords-3", name: "Three of Swords" },
  { id: "swords-4", name: "Four of Swords" },
  { id: "swords-5", name: "Five of Swords" },
  { id: "swords-6", name: "Six of Swords" },
  { id: "swords-7", name: "Seven of Swords" },
  { id: "swords-8", name: "Eight of Swords" },
  { id: "swords-9", name: "Nine of Swords" },
  { id: "swords-10", name: "Ten of Swords" },
  { id: "swords-11", name: "Page of Swords" },
  { id: "swords-12", name: "Knight of Swords" },
  { id: "swords-13", name: "Queen of Swords" },
  { id: "swords-14", name: "King of Swords" },

  // Pentacles (14)
  { id: "pentacles-1", name: "Ace of Pentacles" },
  { id: "pentacles-2", name: "Two of Pentacles" },
  { id: "pentacles-3", name: "Three of Pentacles" },
  { id: "pentacles-4", name: "Four of Pentacles" },
  { id: "pentacles-5", name: "Five of Pentacles" },
  { id: "pentacles-6", name: "Six of Pentacles" },
  { id: "pentacles-7", name: "Seven of Pentacles" },
  { id: "pentacles-8", name: "Eight of Pentacles" },
  { id: "pentacles-9", name: "Nine of Pentacles" },
  { id: "pentacles-10", name: "Ten of Pentacles" },
  { id: "pentacles-11", name: "Page of Pentacles" },
  { id: "pentacles-12", name: "Knight of Pentacles" },
  { id: "pentacles-13", name: "Queen of Pentacles" },
  { id: "pentacles-14", name: "King of Pentacles" },
];
